name: Continuous Integration

on:
  pull_request:
    branches:
      - main  # PENTING: Pastikan ini nama branch utama Anda (main atau master)

jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Versi lebih baru

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4 # Versi lebih baru
        with:
          node-version: '18.x' # Gunakan versi spesifik, BUKAN matrix
          cache: 'npm' # Menambahkan cache untuk instalasi lebih cepat

      - name: Install dependencies and run test
        run: |
          npm install
          npm run test # Ganti ini ke "npm run ci:test" jika skrip Anda berbeda